# Generated by Django 3.0.6 on 2020-05-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendariopagos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num_pago', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_pago', models.DateField()),
                ('estatus', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'calendariopagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'cuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'transacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Podemos.Grupos')),
            ],
            options={
                'db_table': 'miembros',
                'managed': False,
            },
        ),
    ]
